### ISSUE TITLE
Why not trying to contribute to in6pio?

### ISSUE THREAD

**Issue by theofidry** [jeyser/jeyser-crm#1]

**Comment by Stoakes** [comment]
Hello,

We begin a brand new repository for several reasons :
 - Incipio 1.X works, but is doomed because of code in french + several architecture issues.
 - Our philosophy is different from in6pio. It takes several months to get a good level in Symfony, however a standard term in Junior-Entreprises last about 1 year. Therefore creating an API-based ERP is technologically relevant, but the cost for newcomers seems to be too high. We aim at creating a turnkey solution that could be deployed and adapted easily, without a degree in Computer Science.

**Comment by theofidry** [comment]
>Incipio 1.X works, but is doomed because of code in french + several architecture issues.

Hence the attempt of in6pio 2.x (master)

>We aim at creating a turnkey solution that could be deployed and adapted easily, without a degree in Computer Science.

The problem IMO is always and will always be maintainability. A Junior on its own will never have the skills to built a software maintainable enough to last more than 2-3 years. The philosophy of in6pio was not to make the level of accessibility too hight, but instead have a architecture that can sustain the evolving needs of a J.E. and that once in place does not require as much knowledge as one may think. The idea is actually pretty simple: you have your app, but only served through an API. Then you have your front-end which may be whatever you want, a Symfony app or a full JS serverless one.

I'm not saying the actual version of in6pio master is good enough, actually there is quite a lot of things I would like to change to make it more accessible and usable, but I can't help but to find another (third or forth one?) iteration of an open source ERP/CRM for J.E. is not going to make a difference.

That said, I'm not guaranteeing a business level support. All I wish is to help within the domain of reasonable, so if you wish to continue your way so be it, just know that I'm ready to answer any question :)
